#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

link() {
    ln -fs "$PWD/$1" ~/
}

cd "$DIR"
for file in .gitconfig .gituser .octaverc .vimrc .zprofile .zshrc
do
    link "$file"
done
